name: "feature Report"
description: "Reportar um feature encontrado."
title: "[feature] ALTERAR para nome do bug que está reportando"
labels: ["feature"]

body:
  - type: markdown
    attributes:
      value: <!-- Describe the feature you'd like. -->
